name: Publish container
on:
  push:
    tags:
      - '*'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build arm64 container"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Generate tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ram042/w3storage
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=tag
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
